name: Notification Service CI

on:
  push:
    paths:
      - 'services/notification-service/**'
      - 'sonar-project.properties'

  pull_request:
    paths:
      - 'services/notification-service/**'
      - 'sonar-project.properties'

jobs:
  notification-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/notification-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: services/notification-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}